---
  - name: MAILCATCHER - install dependencies
    yum:
      name:
        - gcc
        - gcc-c++
        - sqlite-devel
        - ruby-devel
      state: present

  - name: MAILCATCHER - check for mailcatcher
    stat:
      path: '/usr/local/bin/mailcatcher'
    register: mailcatcher_installed

  - name: MAILCATCHER - create /var/log/mailcatcher.log
    file:
      path: /var/log/mailcatcher.log
      owner: root
      group: root
      mode: '0644'
      state: touch

  - name: MAILCATCHER - install latest version of MailCatcher
    command: gem install mailcatcher
    when: not mailcatcher_installed.stat.exists

  - name: MAILCATCHER - install startup script
    template:
      src: etc/systemd/system/mailcatcher.service.j2
      dest: /etc/systemd/system/mailcatcher.service
      owner: root
      group: root
      mode: 0644

  - name: MAILCATCHER - start the service
    service: name=mailcatcher state=started
